language: java

jdk:
  - openjdk8

# Whitelist
branches:  
  only:
    - master

services:  
    # Enable docker service inside travis
    - docker

install:
    # Build the spring boot app and copy the result to the docker folder
    - mvn -U -Dspring.profiles.active=test clean install && cp target/mc-endorsement-service-*.war docker/

before_script:  
    - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"

script:
    # Build the docker image
    - docker build --no-cache -t dmadk/mc-endorsement-service docker
    # Push the image to the repository
    - docker push dmadk/mc-endorsement-service
    # Logout after build
    - docker logout
