# https://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
spring:
    profiles.active: test

# logging
logging.level:
    net.maritimecloud.endorsement: DEBUG
    #org.springframework.web: DEBUG
    #org.springframework.security: DEBUG
    #org.keycloak.adapters: DEBUG

server:
    port: 8870

---

spring:
    profiles: production
# Database setup
    datasource:
        url: jdbc:mysql://localhost/endorsement
        username: endorsement_user
        password: endorsement
        driverClassName: com.mysql.jdbc.Driver
    flyway.baseline-on-migrate: true

---
spring:
    profiles: test
    datasource:
       url: jdbc:h2:mem:test;DB_CLOSE_ON_EXIT=FALSE
       driverClassName: org.h2.Driver
